export const musics = [
    {   
        id:0,
        name:'Keshi',
        image:'./assets/img/keshi.jpg',
        listMusic:[
            {
                id:0,
                src:'./assets/music/Keshi/always.mp3',
                name:'Always',
                image:'./assets/music/Keshi/always.jpg'
            },
            {
                id:1,
                src:'./assets/music/Keshi/drunk.mp3',
                name:'Drunk',
                image:'./assets/music/Keshi/drunk.jpg'
            },
            {
                id:2,
                src:'./assets/music/Keshi/somebody.mp3',
                name:'Somebody',
                image:'./assets/music/Keshi/somebody.jpg'
            }
        ]
    },
    {
        id:1,
        name:'XXXTenaction',
        image:'./assets/img/xxxtenaction.png'
    },
    {
        id:2,
        name:'Vũ',
        image:'./assets/img/vũ.jpg'

    },
]
